### ISSUE TITLE
CUDA版本问题

### ISSUE THREAD

**Issue by xuesongnie** [cnstark/pytorch-docker#13]
我们一台服务器有多人使用，所以原主机的CUDA版本是11.1比较低。我可以直接拉取比较高CUDA版本的镜像使用嘛，比如CUDA11.6。使用的是A100GPU，这样会和原主机不兼容嘛。

**Comment by cnstark** [comment]
可以。宿主机驱动版本匹配就可以，与宿主机的cuda版本无关。容器里面的代码使用的是镜像里面的cuda版本。

建议宿主机的驱动版本可以高一些，以兼容更多cuda版本。

**Comment by xuesongnie** [comment]
感谢感谢^-^，终于搞懂了两个关系~~~
