### ISSUE TITLE
bash: vim: command not found

### ISSUE THREAD

**Issue by QiangZhangCV** [cnstark/pytorch-docker#4]
Thanks for your great work!
I have docker pull some of your images,  meeting the issue :  sudo, vim, as well as  vi command not found. Could you have a check? You can test the latest one : cnstark/pytorch:1.12.1-py3.9.12-cuda11.6.2-ubuntu20.04. 
looking forward to your reply

**Comment by cnstark** [comment]
Hi, thank you for your question!
There is no `vim` or `vi` installed in our image, because our image is a pure version.
You can install it by `apt update && apt install -y vim`.
