### ISSUE TITLE
Req: pytorch_1.13.1_py3.9.16_cuda11.7.1_ubuntu22.04

### ISSUE THREAD

**Issue by bg4xsd** [cnstark/pytorch-docker#5]
Could you add a new build  pytorch_1.13.1_py3.9.16_cuda11.7.1_ubuntu22.04, GPU runtime and pure CPU two images. 
Anyway, thank you very much.

**Comment by cnstark** [comment]
Hi, the images you need have been built, but it was not added to the README.md file. Please pull it yourself.

```shell
docker pull cnstark/pytorch:1.13.1-py3.9.16-ubuntu20.04
docker pull cnstark/pytorch:1.13.1-py3.9.16-cuda11.7.1-ubuntu20.04
docker pull cnstark/pytorch:1.13.1-py3.9.16-cuda11.7.1-devel-ubuntu20.04
```

**Comment by bg4xsd** [comment]
Thank you, and happy new year.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
