### ISSUE TITLE
Where is the CUDA path?

### ISSUE THREAD

**Issue by QiangZhangCV** [cnstark/pytorch-docker#6]
Thanks for your great work!
I am using the following docker image:
cnstark/pytorch:1.12.0-py3.9.12-cuda11.6.2-ubuntu20.04

I can not found the cuda path. /usr/local/cuda not exisits. As onnxruntime, TensorRT need the cuda well installed, could you provide more informations about this?

**Comment by cnstark** [comment]
Hi!
This version does not contain CUDA files, it is built on the standard Ubuntu image.
Please use `cnstark/pytorch:1.12.0-py3.9.12-cuda11.6.2-devel-ubuntu20.04` instead of the current image.

**Comment by QiangZhangCV** [comment]
Right, Got it. Thanks very much!
