### ISSUE TITLE
Pytorch Versions 里面，没有pytorch版本支持CUDA11.2的

### ISSUE THREAD

**Issue by nianliunian** [cnstark/pytorch-docker#9]
hi，[昊長大人]：
pytorch的版本里面，没有找到支持cuda11.2的，导致生成sh失败，看看是否可以添加更新？
Thx

**Comment by cnstark** [comment]
pytorch官方没有release cuda11.2的安装包，具体可以看https://pytorch.org/get-started/previous-versions/。
如果必须要用cuda11.2，只能自己下载源码编译。如果不是有特殊需求的话，新的cuda版本通常是可以向前兼容的，可以选择11.3替代
